### ISSUE TITLE
Add AppCenter screenshot showing spell-check feature

### ISSUE THREAD

**Issue by aral** [small-tech/comet#14]
## Tasks

  - [x] English
  - [x] Turkish
  - [x] Nederlands

**Comment by aral** [comment]
@sexybiggetje I’ve added a line of copy for the new AppCenter screenshot showcasing the spell-check feature here:

https://github.com/small-tech/comet/blob/735424b586510af1e59bbfe938d9c08857437ff9/po/nl.po#L260

It’s “Highlights splling mstakes” with “spelling mistakes” purposefully misspelled.

Would you be kind enough to translate it when you get a moment? :)

(Please feel free to reply here and I’ll be happy to include it, you don’t have to prepare a pull request.) :)

**Comment by sexybiggetje** [comment]
Markeert spl fuoten
Or
Markeert spllingsfoutn

But the first one is more clear what the intention was (Markeert spelfouten would be correctly written)

**Comment by aral** [comment]
@sexybiggetje Thank you so much :)

The automated screenshot script is working like a charm now (and is a joy to watch – will record a video and do a write-up soon).

Going to add these translations to it now and then I think I’m pretty much ready to submit this to the elementary folks for inclusion in the AppCenter.

Thank you again for your help :)
