### ISSUE TITLE
Update translations block with instructions for translation with other tools

### ISSUE THREAD

**Issue by sexybiggetje** [small-tech/comet#16]
Hey,

If one would want to translate the app with POEdit, it could work as followed;

1. Add the language code to the po/LINGUAS file.
2. Open POEdit
3. On the launch screen select Create new... (Create new translation from POT template.)
4. Select the file po/org.small_tech.comet.pot
5. In the popup select your target language

A pre-translation feature is available for a paid license, it's reasonably well but needs good review, since some translations are bad.

POEdit by default also generates the related .mo file, this isn't used so best to not add it to the repository.

**Comment by aral** [comment]
Thanks @sexybiggetje – added to the readme :) :two_hearts:
