### ISSUE TITLE
Name/icon almost identical to Reddit client app

### ISSUE THREAD

**Issue by deusnovus** [small-tech/comet#29]
Hello friends, I don't know whether this was an intentional choice or not, but the app's name and icon is almost identical to a popular Reddit client for iOS. Just wanted to bring this to your attention, for future reference.

![comet](https://github.com/small-tech/comet/assets/32219080/c2da9098-d1e1-4e1b-ad76-cf1238adf9de)

**Comment by aral** [comment]
Heya, thanks for the heads up but such things are bound to happen. Comet is a play on “commit”.
